name: www.hubhero.net

sass:
  sass_dir: css

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

excerpt_separator: <!--break-->

navigation:
  - title: Features
    url: /features/
  - title: Pricing
    url: /pricing/
  - title: Free trial
    url: /trial/

collections:
  trainings:
    output: true

title: Hub Hero
author: Wild Tree Tech
description: Hosted multi user Jupyter notebooks

url: https://www.hubhero.net
logo: /images/logo.svg

twitter:
  username: wildtreetech

exclude: [vendor]
include: [_redirects]

defaults:
  -
    scope:
      path: ""
    values:
      image:
        twitter: /images/logo.svg
        facebook: /images/logo.svg
        height: 144
        width: 144
